[tox]
envlist = py39, py310, py311, py312, py313, py314
min_version = 4.0
requires = tox-uv
skipsdist = true

[testenv]
uv_sync = true
deps =
    .
    .[test]
commands =
    pytest -m "not slow" -n 2 --dist=loadfile {posargs}
passenv = *
setenv =
    PYTHONPATH = {toxinidir}/src
    PYTHONDONTWRITEBYTECODE = 1
    QT_QPA_PLATFORM = offscreen
